/*
 Navicat Premium Data Transfer

 Source Server         : QSQLITE
 Source Server Type    : SQLite
 Source Server Version : 3021000
 Source Schema         : main

 Target Server Type    : SQLite
 Target Server Version : 3021000
 File Encoding         : 65001

 Date: 12/10/2024 13:59:49
*/

PRAGMA foreign_keys = false;

-- ----------------------------
-- Table structure for MacroSettingPara_0
-- ----------------------------
DROP TABLE IF EXISTS "MacroSettingPara_0";
CREATE TABLE "MacroSettingPara_0" (
  "Macro" text,
  "Pos" TEXT,
  "No" text,
  "Type" text,
  "File" TEXT,
  "m_Group" TEXT
);

-- ----------------------------
-- Records of MacroSettingPara_0
-- ----------------------------
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No1', 10, 0, 'M10.NCC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No2', 6, 0, 'M06.NCC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No3', 56, 0, 'M56.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No4', 57, 0, 'M57.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No5', 87, 0, 'M87.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No6', 88, 0, 'M88.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No7', 89, 0, 'M89.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No8', 300, 0, 'M300.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No9', 301, 0, 'M301.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No10', 302, 0, 'M302.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No11', 303, 0, 'M303.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No12', 304, 0, 'M304.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No13', 305, 0, 'M305.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No14', 306, 0, 'M306.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No15', 307, 0, 'M307.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No16', 310, 0, 'M310.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No17', 311, 0, 'M311.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No18', 312, 0, 'M312.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No19', 313, 0, 'M313.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No20', 1002, 0, 'M1002.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No21', 231, 0, 'M231.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No22', 232, 0, 'M232.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No23', 233, 0, 'M233.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No24', 234, 0, 'M234.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No25', 320, 0, 'M320.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No26', 321, 0, 'M321.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No27', 322, 0, 'M322.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No28', 323, 0, 'M323.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No29', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No30', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No31', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No32', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No33', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No34', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No35', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No36', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No37', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No38', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No39', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No40', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No41', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No42', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No43', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No44', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No45', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No46', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No47', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No48', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No49', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No50', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No51', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No52', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No53', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No54', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No55', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No56', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No57', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No58', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No59', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No60', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No61', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No62', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No63', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No64', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No65', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No66', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No67', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No68', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No69', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No70', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No71', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No72', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No73', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No74', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No75', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No76', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No77', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No78', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No79', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No80', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No81', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No82', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No83', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No84', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No85', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No86', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No87', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No88', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No89', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No90', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No91', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No92', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No93', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No94', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No95', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No96', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No97', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No98', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No99', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('M_Macro', 'No100', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No1', 84, 1, 'G84.NCC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No2', 81, 1, 'G81.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No3', 82, 1, 'G82.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No4', 84200, 0, 'G84200.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No5', 83, 1, 'G83.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No6', 78, 1, 'G78.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No7', 79, 1, 'G79.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No8', 88, 1, 'G88.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No9', 89, 1, 'G89.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No10', 84300, 0, 'G84300.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No11', 283, 1, 'G283.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No12', 284, 1, 'G284.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No13', 287, 1, 'G287.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No14', 288, 1, 'G288.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No15', 284200, 0, 'G284200.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No16', 288200, 0, 'G288200.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No17', 285, 1, 'G285.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No18', 289, 1, 'G289.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No19', 290, 1, 'G290.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No20', 294, 1, 'G294.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No21', 85, 1, 'G85.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No22', 86, 1, 'G86.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No23', 87, 1, 'G87.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No24', 73, 1, 'G73.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No25', 74, 1, 'G74.NCC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No26', 75, 1, 'G75.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No27', 76, 1, 'G76.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No28', 77, 1, 'G77.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No29', 71100, 0, 'G71100.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No30', 72100, 0, 'G72100.NC', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No31', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No32', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No33', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No34', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No35', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No36', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No37', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No38', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No39', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No40', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No41', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No42', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No43', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No44', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No45', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No46', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No47', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No48', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No49', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No50', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No51', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No52', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No53', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No54', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No55', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No56', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No57', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No58', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No59', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No60', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No61', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No62', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No63', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No64', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No65', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No66', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No67', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No68', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No69', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No70', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No71', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No72', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No73', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No74', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No75', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No76', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No77', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No78', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No79', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No80', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No81', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No82', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No83', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No84', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No85', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No86', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No87', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No88', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No89', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No90', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No91', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No92', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No93', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No94', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No95', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No96', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No97', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No98', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No99', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('G_Macro', 'No100', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No1', 1, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No2', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No3', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No4', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No5', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No6', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No7', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No8', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No9', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No10', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No11', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No12', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No13', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No14', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No15', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No16', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No17', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No18', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No19', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No20', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No21', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No22', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No23', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No24', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No25', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No26', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No27', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No28', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No29', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No30', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No31', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No32', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No33', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No34', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No35', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No36', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No37', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No38', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No39', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No40', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No41', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No42', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No43', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No44', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No45', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No46', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No47', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No48', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No49', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No50', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No51', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No52', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No53', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No54', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No55', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No56', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No57', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No58', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No59', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No60', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No61', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No62', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No63', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No64', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No65', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No66', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No67', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No68', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No69', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No70', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No71', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No72', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No73', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No74', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No75', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No76', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No77', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No78', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No79', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No80', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No81', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No82', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No83', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No84', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No85', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No86', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No87', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No88', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No89', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No90', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No91', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No92', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No93', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No94', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No95', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No96', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No97', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No98', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No99', 0, 0, '', 0);
INSERT INTO "MacroSettingPara_0" VALUES ('T_Macro', 'No100', 0, 0, '', 0);

PRAGMA foreign_keys = true;
